- hosts: Leaves
  connection: local
  gather_facts: no

  tasks:
    - name: Building Leaves configs
      template:
        src=templates/leaf.j2
        dest=host_vars/{{inventory_hostname}}.yaml

- hosts: Spines
  connection: local
  gather_facts: no

  tasks:
    - name: Building Spines configs
      template:
        src=templates/spine.j2
        dest=host_vars/{{inventory_hostname}}.yaml

- hosts: Borders
  connection: local
  gather_facts: no

  tasks:
    - name: Building Borders  configs
      template:
        src=templates/border.j2
        dest=host_vars/{{inventory_hostname}}.yaml

- hosts: Routers
  connection: local
  gather_facts: no

  tasks:
    - name: Building Routers  configs
      template:
        src=templates/router.j2
        dest=host_vars/{{inventory_hostname}}.yaml


